name: kevin austin dugger
favicon: null
layout_spectrum: 0.2514
typography_spectrum: 0.231
title: 'Portfolio '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#262626'
    - '#dadada'
    - '#c0c0c0'
    - '#8d8d8d'
    - '#727272'
  brandStrength: 1
  lightness: 0.5625
  saturation: 0.75
  rhythmicContrast: 1
purpose: []
