name: portfoliostream
favicon: null
layout_spectrum: 0.8448165666777641
typography_spectrum: 0.3042476107366383
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#262626'
    - '#dadada'
    - '#c0c0c0'
    - '#8d8d8d'
    - '#727272'
  brandStrength: 0.75
  lightness: 0.5
  saturation: 0.6875
  rhythmicContrast: 0.75
purpose: []
